name: Build, Test, and Deploy

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build_and_test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn -e -B package --file pom.xml

      - name: Run JUnit tests
        run: mvn test

      - name: Test with Maven
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t apoorvnv/demo_tictactoe_java_pipeline:latest .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push apoorvnv/demo_tictactoe_java_pipeline:latest
